languageCode = "en-us"
title = "Florent Collin"
rssLimit = 20
copyright = "2022 Florent Collin All rights reserved"
minify = false

theme = ["hugo-video"]

[Author]
    name = "FlorentCollin"
    email = "florentcollinpro@gmail.com"

[permalinks]
    posts = "/:year/:month/:day/:filename"
    pages = "/:slug"

[taxonomies]
    tag = "tags"
    category = "categories"

[outputs]
    home = ["html", "json", "rss"]

[markup]
[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'doom-one2'
    tabWidth = 4
