#+TITLE: Florent Collin
#+SUBTITLE: Master Student in Computer Science
#+AUTHOR: Florent Collin
#+OPTIONS: toc:nil num:nil html-postamble:nil html-style:nil ^:nil
    #+HTML_HEAD: <link rel="stylesheet" type="text/css" href="about.css" />

**Hey there ! 👋**
#+begin_quote
I'm a student developer at UMons with a back-end experience, I am currently focusing on learning low-level programming, graphics rendering and graphics manipulation.
I'm also interested in classical AI and there applications in games.
For my master degree, I'm working on a analysis of scheduling functions for Low-Power and Lossy Networks.

Currently searching for an internship, so feel free to [[mailto:florentcollinpro@gmail.com][reach me !]]
#+end_quote

** Work Experience
*Student Assistant • UMons (Mons, 2020 - 2021)*
- Assisted 80 first-year students during their hands-on programming and algorithmic courses in Python and Java.

*Algorithms Lab's Intern • UMons (Mons, August 2020)*
- Developed and implemented a time-based shortest path algorithm in C++ using QGIS and OpenStreetMap.
- Optimized the code to calculate in the order of milliseconds the fastest paths to reach any node in a city graph with thousands of nodes and edges.

*Back-end Developer • Open Summer of Code (Remote, July 2020)* | [[https://osoc.be/editions/2020/simplification-election-procedures][WEBSITE]]
- Built a system to decentralize electoral data and provide a simple interface for citizens to access that data.
- Designed and implemented the data pipeline from the candidate forms to the front-end using Link Data, Solid and a Python API.

*Back-end Developer • Open Summer of Code (Brussels, July 2019)* | [[https://osoc.be/editions/2019/data-monitor][WEBSITE]]
- Built a Node.Js/React website that shows the quality of Dutch mobility data on a map.
- Developed the back-end server using PostGIS to process geospatial queries.

*Student Assistant • UMons (Mons, August 2018)*
- Organized lessons that enabled students to successfully complete their first year in
computer science, math and physics.

** Projects
*Scheduling Functions in Wireless Sensors Network (2020 - 2021)*
- Analyzed the behavior of diﬀerent scheduling functions for Wireless Sensors Networks in a simulator.

*Community Detection in Graphs (2020)*
- Built an evolutionary algorithm in Python that solves the community detection problem.
- Implemented a multi-threading version which has greatly increased performances.

*Multiplayer turn-based Game • Slay (2019)* | [[https://github.com/FlorentCollin/Slay-Groupe1-PGL-2018-2019][GITHUB]]
- Developed a multiplayer game over a network connection where each player must ﬁght their enemies with soldiers to gain territory.
- A server was developed in Java with a multi-threaded approach to handle several game rooms concurrently.

*Puzzle Game • Baba is You (2018)* | [[https://github.com/FlorentCollin/baba-is-you][GITHUB]]
- Recreated the first levels of the famous game: Baba is You. A puzzle game where the player can change the rules by pushing blocks and win in many different ways.

** Relevant Courses
    - Graphs & Artificial Intelligence
    - Databases
    - Networks
    - Compilers
    - Combinatorial Optimization
    - Model Checking